%YAML:1.0
# data
# KITTI dataset directory, change it to yours! 
dataset_dir: /mnt/f/Dataset/KITTI/data/sequence/01

# Image size, expected same for both cameras
img_width: 1241
img_height: 376

# camera intrinsics
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

# Feature parameter
num_features: 300
num_features_init: 100
num_features_tracking: 50

# ORB parameter
# Check https://docs.opencv.org/3.4/db/d95/classcv_1_1ORB.html
# for specific parameter meaning
scale_factor: 1.2
pyramid_level: 8
edge_threshold: 31
first_level: 0
wta_k: 2
patch_size: 31
fast_thresh: 20

# Save estimated trajectory
# 0: false
# 1: true
save_trajectory: 1

# Enable data visulization
# 0: false
# 1: true
enable_viewer: 1